# Generated by Django 2.1.2 on 2018-10-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtstart', models.DateTimeField(verbose_name='Startzeit')),
                ('dtend', models.DateTimeField(verbose_name='Endzeit')),
                ('summary', models.CharField(max_length=250, verbose_name='Kalendereintrag')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Raumbezeichnung nach WebUntis')),
                ('url', models.URLField(max_length=300, verbose_name='Webuntis URL')),
                ('dtchanged', models.DateTimeField(null=True, verbose_name='Letzte Änderung')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webuntis.Room'),
        ),
    ]
