# Generated by Django 2.1.2 on 2018-10-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuntis', '0002_event_dtcreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dtcreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
